# robot_localization EKF configuration placeholder
# Reference: https://docs.ros.org/en/humble/p/robot_localization

ekf_filter_node:
  ros__parameters:
    frequency: 50.0
    sensor_timeout: 0.2
    two_d_mode: true
    publish_tf: false  # Let pub_odom handle TF, EKF only outputs filtered odometry
    map_frame: map
    odom_frame: odom
    base_link_frame: base_footprint
    world_frame: odom

    # Allow TF lookups with time offset to handle LiDAR timestamp lag
    transform_timeout: 0.0
    transform_time_offset: 0.0

    odom0: /odom
    odom0_config: [true,  true,  false,
                   false, false, true,
                   true,  false, false,
                   false, false, true,
                   false, false, false]
    odom0_queue_size: 5
    odom0_differential: false

    imu0: /mid360/imu
    imu0_config: [false, false, false,
                  true, true, true,
                  false, false, false,
                  true, true, true,
                  false, false, false]
    imu0_queue_size: 10
    imu0_relative: false
    imu0_remove_gravitational_acceleration: false

    use_control: false
    debug: false
