# RTABMAP配置 - 仅里程计模式
# 用于传感器故障时的降级运行

rtabmap:
  ros__parameters:
    # 基础配置
    frame_id: "base_link"
    odom_frame_id: "odom"
    map_frame_id: "map"
    publish_tf: true
    tf_delay: 0.02
    use_sim_time: false

    # 订阅配置 - 仅里程计
    subscribe_depth: false
    subscribe_rgb: false
    subscribe_scan: false
    subscribe_scan_cloud: false
    subscribe_stereo: false
    subscribe_rgbd: false
    subscribe_odom_info: true
    approx_sync: false

    # 话题配置
    odom_topic: "/odom"

    # 队列大小
    queue_size: 10
    sync_queue_size: 10

    # QoS设置
    qos: 1
    qos_odom: 1

    # RTABMAP核心参数 - 最小化配置
    Rtabmap/DetectionRate: "0.5"        # 降低频率节省资源
    Rtabmap/CreateIntermediateNodes: "false"
    Rtabmap/MaxRetrieved: "1"
    Rtabmap/MemoryThr: "100"            # 限制内存使用
    Rtabmap/LoopThr: "0.15"

    # 禁用所有传感器相关功能
    Reg/Strategy: "0"                    # Visual (但无数据)
    Reg/Force3DoF: "true"

    # 禁用视觉特征
    Vis/EstimationType: "1"
    Vis/MaxFeatures: "0"

    # 禁用ICP
    Icp/Strategy: "0"

    # 基础栅格地图（仅基于里程计）
    Grid/3D: "false"
    Grid/RayTracing: "false"            # 无传感器数据
    Grid/RangeMin: "0.0"
    Grid/RangeMax: "5.0"
    Grid/CellSize: "0.1"                # 较大网格
    Grid/PreVoxelFiltering: "false"
    Grid/FromDepth: "false"
    Grid/Sensor: "-1"                   # 无传感器

    # 内存管理 - 最小化
    Mem/RehearsalSimilarity: "0.5"
    Mem/UseOdomFeatures: "false"
    Mem/NotLinkedNodesKept: "false"
    Mem/STMSize: "10"
    Mem/IncrementalMemory: "true"
    Mem/ReduceGraph: "true"

    # 简单优化
    Optimizer/Strategy: "0"               # TORO
    Optimizer/Iterations: "50"
    Optimizer/Epsilon: "0.0001"

    # 里程计参数
    Odom/Strategy: "0"
    Odom/ResetCountdown: "1"            # 快速重置
    Odom/Holonomic: "false"
    Odom/FilteringStrategy: "0"
    Odom/GuessMotion: "true"

    # 发布选项 - 最小化
    Rtabmap/PublishStats: "false"
    Rtabmap/PublishLastSignature: "false"
    Rtabmap/PublishPdf: "false"
    Rtabmap/PublishLikelihood: "false"