# TG30 parameters
# https://github.com/YDLIDAR/ydlidar_ros2_driver/blob/master/details.md

ydlidar_ros2_driver_node:
  ros__parameters:
    port: /dev/ttyUSB1  # Set the port to the respective port of the LRF sensor.
    frame_id: front_lrf_link
    ignore_array: ""  # to remove ROS PC region: "140, 180, -180, -140"
    baudrate: 512000
    lidar_type: 0
    device_type: 0
    intensity_bit: 0
    sample_rate: 20
    abnormal_check_count: 4
    fixed_resolution: true
    reversion: true
    inverted: true
    auto_reconnect: true
    isSingleChannel: false
    intensity: false
    support_motor_dtr: false
    angle_max: 180.0
    angle_min: -180.0
    range_max: 30.0
    range_min: 0.01
    frequency: 10.0
    invalid_range_is_inf: false

